apiVersion: v1
kind: ServiceAccount
metadata:
  name: dra-sriov
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dra-sriov
rules:
- apiGroups: ["resource.k8s.io"]
  resources: ["resourceslices"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: ["resource.k8s.io"]
  resources: ["resourceclaims"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get","list","watch"]
- apiGroups: ["sriovnetwork.k8snetworkplumbingwg.io"]
  resources: ["sriovresourcepolicies"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dra-sriov
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dra-sriov
subjects:
- kind: ServiceAccount
  name: dra-sriov
  namespace: kube-system
---
apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: sriovnetwork.k8snetworkplumbingwg.io
spec:
  selectors:
  - cel:
      expression: "device.driver == \"sriovnetwork.k8snetworkplumbingwg.io\""
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dra-sriov
  namespace: kube-system
  labels:
    app: dra-sriov
spec:
  selector:
    matchLabels:
      app: dra-sriov
  template:
    metadata:
      labels:
        app: dra-sriov
    spec:
      priorityClassName: system-node-critical
      hostNetwork: true
      tolerations:
      - operator: Exists
      serviceAccountName: dra-sriov
      containers:
      - name: dra-sriov
        image: localhost/dra-sriov-driver:standardized-v3
        imagePullPolicy: Never
        args:
        - --hostname-override=$(NODE_NAME)
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - name: plugins
          mountPath: /var/lib/kubelet/plugins
        - name: plugins-registry
          mountPath: /var/lib/kubelet/plugins_registry
        - name: cdi
          mountPath: /var/run/cdi
        - name: sys
          mountPath: /sys
      volumes:
      - name: plugins
        hostPath:
          path: /var/lib/kubelet/plugins
      - name: plugins-registry
        hostPath:
          path: /var/lib/kubelet/plugins_registry
      - name: cdi
        hostPath:
          path: /var/run/cdi
          type: DirectoryOrCreate
      - name: sys
        hostPath:
          path: /sys
