{{- if .Values.cpu.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dracpu
  namespace: {{ .Release.Namespace }}
  labels:
    app: dracpu
    {{- include "dra-topology-drivers.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: dracpu
  template:
    metadata:
      labels:
        app: dracpu
    spec:
      priorityClassName: system-node-critical
      tolerations:
      - operator: Exists
      serviceAccountName: dracpu
      hostPID: true
      containers:
      - name: dracpu
        image: {{ .Values.cpu.image.repository }}:{{ .Values.cpu.image.tag }}
        imagePullPolicy: {{ .Values.cpu.image.pullPolicy }}
        args:
        - --v={{ .Values.cpu.verbosity }}
        - --cpu-device-mode={{ .Values.cpu.deviceMode }}
        - --hostname-override=$(NODE_NAME)
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - name: plugins
          mountPath: /var/lib/kubelet/plugins
        - name: plugins-registry
          mountPath: /var/lib/kubelet/plugins_registry
        - name: nri
          mountPath: /var/run/nri
        - name: cdi
          mountPath: /var/run/cdi
      volumes:
      - name: plugins
        hostPath:
          path: /var/lib/kubelet/plugins
      - name: plugins-registry
        hostPath:
          path: /var/lib/kubelet/plugins_registry
      - name: nri
        hostPath:
          path: /var/run/nri
      - name: cdi
        hostPath:
          path: /var/run/cdi
          type: DirectoryOrCreate
{{- end }}
