apiVersion: v1
items:
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    annotations:
      deprecated.daemonset.template.generation: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"name":"dracpu","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"app":"dracpu"}},"template":{"metadata":{"labels":{"app":"dracpu"}},"spec":{"containers":[{"args":["--hostname-override=$(NODE_NAME)","--group-by=numanode"],"env":[{"name":"NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}}],"image":"localhost/dra-cpu-driver:standardized","imagePullPolicy":"Never","name":"dracpu","securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/var/lib/kubelet/plugins_registry","name":"plugins-registry"},{"mountPath":"/var/lib/kubelet/plugins/dra.cpu","name":"plugins"},{"mountPath":"/sys","name":"sys","readOnly":true},{"mountPath":"/var/run/nri","name":"nri"}]}],"tolerations":[{"operator":"Exists"}],"volumes":[{"hostPath":{"path":"/var/lib/kubelet/plugins_registry"},"name":"plugins-registry"},{"hostPath":{"path":"/var/lib/kubelet/plugins/dra.cpu","type":"DirectoryOrCreate"},"name":"plugins"},{"hostPath":{"path":"/sys"},"name":"sys"},{"hostPath":{"path":"/var/run/nri"},"name":"nri"}]}}}}
    creationTimestamp: "2026-04-23T18:53:38Z"
    generation: 1
    name: dracpu
    namespace: kube-system
    resourceVersion: "12921"
    uid: b9441965-e734-4368-bc1f-c06e0e5335da
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: dracpu
    template:
      metadata:
        labels:
          app: dracpu
      spec:
        containers:
        - args:
          - --hostname-override=$(NODE_NAME)
          - --group-by=numanode
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          image: localhost/dra-cpu-driver:standardized
          imagePullPolicy: Never
          name: dracpu
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/kubelet/plugins_registry
            name: plugins-registry
          - mountPath: /var/lib/kubelet/plugins/dra.cpu
            name: plugins
          - mountPath: /sys
            name: sys
            readOnly: true
          - mountPath: /var/run/nri
            name: nri
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        tolerations:
        - operator: Exists
        volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: ""
          name: plugins-registry
        - hostPath:
            path: /var/lib/kubelet/plugins/dra.cpu
            type: DirectoryOrCreate
          name: plugins
        - hostPath:
            path: /sys
            type: ""
          name: sys
        - hostPath:
            path: /var/run/nri
            type: ""
          name: nri
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
  status:
    currentNumberScheduled: 1
    desiredNumberScheduled: 1
    numberAvailable: 1
    numberMisscheduled: 0
    numberReady: 1
    observedGeneration: 1
    updatedNumberScheduled: 1
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    annotations:
      deprecated.daemonset.template.generation: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"name":"dramemory","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"app":"dramemory"}},"template":{"metadata":{"labels":{"app":"dramemory"}},"spec":{"containers":[{"args":["--hostname-override=$(NODE_NAME)"],"env":[{"name":"NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}}],"image":"localhost/dra-memory-driver:standardized","imagePullPolicy":"Never","name":"dramemory","securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/var/lib/kubelet/plugins_registry","name":"plugins-registry"},{"mountPath":"/var/lib/kubelet/plugins/dra.memory","name":"plugins"},{"mountPath":"/sys","name":"sys","readOnly":true},{"mountPath":"/var/run/nri","name":"nri"}]}],"tolerations":[{"operator":"Exists"}],"volumes":[{"hostPath":{"path":"/var/lib/kubelet/plugins_registry"},"name":"plugins-registry"},{"hostPath":{"path":"/var/lib/kubelet/plugins/dra.memory","type":"DirectoryOrCreate"},"name":"plugins"},{"hostPath":{"path":"/sys"},"name":"sys"},{"hostPath":{"path":"/var/run/nri"},"name":"nri"}]}}}}
    creationTimestamp: "2026-04-23T19:00:58Z"
    generation: 2
    name: dramemory
    namespace: kube-system
    resourceVersion: "12923"
    uid: 7719d790-1f81-4154-bcd3-cff5aca83d45
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: dramemory
    template:
      metadata:
        labels:
          app: dramemory
      spec:
        containers:
        - args:
          - --hostname-override=$(NODE_NAME)
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          image: localhost/dra-memory-driver:standardized-v2
          imagePullPolicy: Never
          name: dramemory
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/kubelet/plugins_registry
            name: plugins-registry
          - mountPath: /var/lib/kubelet/plugins/dra.memory
            name: plugins
          - mountPath: /sys
            name: sys
            readOnly: true
          - mountPath: /var/run/nri
            name: nri
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        tolerations:
        - operator: Exists
        volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: ""
          name: plugins-registry
        - hostPath:
            path: /var/lib/kubelet/plugins/dra.memory
            type: DirectoryOrCreate
          name: plugins
        - hostPath:
            path: /sys
            type: ""
          name: sys
        - hostPath:
            path: /var/run/nri
            type: ""
          name: nri
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
  status:
    currentNumberScheduled: 1
    desiredNumberScheduled: 1
    numberAvailable: 1
    numberMisscheduled: 0
    numberReady: 1
    observedGeneration: 2
    updatedNumberScheduled: 1
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    annotations:
      deprecated.daemonset.template.generation: "3"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"name":"dra-sriov","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"app":"dra-sriov"}},"template":{"metadata":{"labels":{"app":"dra-sriov"}},"spec":{"containers":[{"args":["--node-name=$(NODE_NAME)"],"env":[{"name":"NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}}],"image":"localhost/dra-sriov-driver:standardized","imagePullPolicy":"Never","name":"dra-sriov","securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/var/lib/kubelet/plugins_registry","name":"plugins-registry"},{"mountPath":"/var/lib/kubelet/plugins/sriovnetwork.k8snetworkplumbingwg.io","name":"plugins"},{"mountPath":"/var/run/cdi","name":"cdi"},{"mountPath":"/sys","name":"sys"},{"mountPath":"/var/run/nri","name":"nri"}]}],"tolerations":[{"operator":"Exists"}],"volumes":[{"hostPath":{"path":"/var/lib/kubelet/plugins_registry"},"name":"plugins-registry"},{"hostPath":{"path":"/var/lib/kubelet/plugins/sriovnetwork.k8snetworkplumbingwg.io","type":"DirectoryOrCreate"},"name":"plugins"},{"hostPath":{"path":"/var/run/cdi","type":"DirectoryOrCreate"},"name":"cdi"},{"hostPath":{"path":"/sys"},"name":"sys"},{"hostPath":{"path":"/var/run/nri"},"name":"nri"}]}}}}
    creationTimestamp: "2026-04-23T19:36:15Z"
    generation: 3
    name: dra-sriov
    namespace: kube-system
    resourceVersion: "15111"
    uid: bc19cc25-9f40-474d-aa49-72a0379bf563
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: dra-sriov
    template:
      metadata:
        labels:
          app: dra-sriov
      spec:
        containers:
        - args:
          - --node-name=$(NODE_NAME)
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          image: localhost/dra-sriov-driver:standardized-v3
          imagePullPolicy: Never
          name: dra-sriov
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/kubelet/plugins_registry
            name: plugins-registry
          - mountPath: /var/lib/kubelet/plugins/sriovnetwork.k8snetworkplumbingwg.io
            name: plugins
          - mountPath: /var/run/cdi
            name: cdi
          - mountPath: /sys
            name: sys
          - mountPath: /var/run/nri
            name: nri
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        tolerations:
        - operator: Exists
        volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: ""
          name: plugins-registry
        - hostPath:
            path: /var/lib/kubelet/plugins/sriovnetwork.k8snetworkplumbingwg.io
            type: DirectoryOrCreate
          name: plugins
        - hostPath:
            path: /var/run/cdi
            type: DirectoryOrCreate
          name: cdi
        - hostPath:
            path: /sys
            type: ""
          name: sys
        - hostPath:
            path: /var/run/nri
            type: ""
          name: nri
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
  status:
    currentNumberScheduled: 1
    desiredNumberScheduled: 1
    numberAvailable: 1
    numberMisscheduled: 0
    numberReady: 1
    observedGeneration: 3
    updatedNumberScheduled: 1
kind: List
metadata:
  resourceVersion: ""
