apiVersion: v1
items:
- apiVersion: sriovnetwork.k8snetworkplumbingwg.io/v1alpha1
  kind: SriovResourcePolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"sriovnetwork.k8snetworkplumbingwg.io/v1alpha1","kind":"SriovResourcePolicy","metadata":{"annotations":{},"name":"cx7-policy","namespace":"dra-driver-sriov"},"spec":{"configs":[{"deviceAttributesSelector":{"matchLabels":{"pool":"cx7"}},"resourceFilters":[{"pfNames":["enp55s0np0"],"vendors":["15b3"]}]}]}}
    creationTimestamp: "2026-04-23T19:46:31Z"
    generation: 1
    name: cx7-policy
    namespace: dra-driver-sriov
    resourceVersion: "15055"
    uid: 6df9291d-4879-4a66-889a-5f7685ac4231
  spec:
    configs:
    - deviceAttributesSelector:
        matchLabels:
          pool: cx7
      resourceFilters:
      - pfNames:
        - enp55s0np0
        vendors:
        - 15b3
- apiVersion: sriovnetwork.k8snetworkplumbingwg.io/v1alpha1
  kind: SriovResourcePolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"sriovnetwork.k8snetworkplumbingwg.io/v1alpha1","kind":"SriovResourcePolicy","metadata":{"annotations":{},"name":"default","namespace":"dra-driver-sriov"},"spec":{}}
    creationTimestamp: "2026-04-23T19:45:15Z"
    generation: 1
    name: default
    namespace: dra-driver-sriov
    resourceVersion: "14850"
    uid: 0990ece9-7e7f-4fb8-86dc-4f35c51731f8
  spec: {}
kind: List
metadata:
  resourceVersion: ""
apiVersion: v1
items:
- apiVersion: sriovnetwork.k8snetworkplumbingwg.io/v1alpha1
  kind: DeviceAttributes
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"sriovnetwork.k8snetworkplumbingwg.io/v1alpha1","kind":"DeviceAttributes","metadata":{"annotations":{},"labels":{"pool":"cx7"},"name":"cx7-attrs","namespace":"dra-driver-sriov"},"spec":{"attributes":{"sriovnetwork.k8snetworkplumbingwg.io/resourceName":{"string":"cx7_vf"}}}}
    creationTimestamp: "2026-04-23T19:46:31Z"
    generation: 1
    labels:
      pool: cx7
    name: cx7-attrs
    namespace: dra-driver-sriov
    resourceVersion: "15054"
    uid: 8a8e216a-f726-4347-940e-7001ac98ff5a
  spec:
    attributes:
      sriovnetwork.k8snetworkplumbingwg.io/resourceName:
        string: cx7_vf
kind: List
metadata:
  resourceVersion: ""
