apiVersion: resource.k8s.io/v1
kind: ResourceClaim
metadata:
  name: demo-3-eighths
  namespace: default
spec:
  devices:
    requests:
    - name: partitions
      exactly:
        deviceClassName: eighth
        count: 3
